### ISSUE TITLE
Adding Y-level Chunk Borders

### ISSUE THREAD

**Issue by tentyped** [EvanatorM/ScuffedMinecraft#1]
I was looking at the game recently (AKA. just 5 minutes ago) and noticed that chunks don't exactly have a Y limit (Haven't read the code enough to check yet). I recommend adding explicit limits in the chunk structure, especially for the lower Y, as it's generally useless to not limit it. You could also replicate Minecraft  by using the random library and putting a 75% chance that it will spawn in a specific block (make sure not to have overlapping blocks) for 3 blocks above the limit and just a normal filled bedrock layer at the bottom.

**Comment by EvanatorM** [comment]
Thanks for checking out the code! The chunks are all 32 blocks tall. I know that the infinite height is useless, but I decided to keep it for now because it's cool to say my world has infinite height. I'll definitely limit it if I start actually making a game out of this project.

**Comment by Unavailed** [comment]
Honestly the no height limit may be actually useful for builders if they want to build large structures, but its the bottom Y that's the problem. There's no limit to how deep you can mine. I'd recommend adding a minimum Y level and building the chunk up from there

**Comment by EvanatorM** [comment]
Yeah I'm hoping to eventually make a game out of this (that'll be different from Minecraft lol) so I will definitely add a limit to it then. For now though, this is kinda just a simple little engine, so I'm just going to leave it for now
