### ISSUE TITLE
Aspect-ratio issues

### ISSUE THREAD

**Issue by raymonable** [EvanatorM/ScuffedMinecraft#11]
Not sure if this also occurs on Windows, but I am on Linux and when I resize the window, the viewport doesn't shape correctly.
![image](https://github.com/user-attachments/assets/22611f31-b6bc-431b-8ef1-bf74996c7015)
![image](https://github.com/user-attachments/assets/ea98ceb6-c57a-4c90-a451-152a5b115509)

![image](https://github.com/user-attachments/assets/78fc29c3-ee1d-4d6a-95b4-05206eb0e805)

**Comment by Luna-devv** [comment]
Can confirm, same on Fedora Linux. (ignore broken chunks)
![image](https://github.com/user-attachments/assets/24337a5b-469f-4e02-90b1-ced9c44fa8f8)

Here is my system information:
![image](https://github.com/user-attachments/assets/83ee4056-2cc8-4f5f-a0a0-75fb6624e38b)
