### ISSUE TITLE
Include and library directory paths

### ISSUE THREAD

**Issue by Resongeo** [EvanatorM/ScuffedMinecraft#2]
I checked out your project and I like it. But when I wanted to build myself I ran into the issue that the `Include` and `Library` directory paths are absolute paths and if someone doesn't has the project in `C:\dev\C++\` it wont find the files.

Using a Visual Studio macro like `$(SolutionDir)` solves this problem.

**Comment by EvanatorM** [comment]
Thanks for checking out the project! This will be fixed in the next episode.

**Comment by EvanatorM** [comment]
This has been resolved
