### ISSUE TITLE
Pre-Alpha 4.0 is a virus

### ISSUE THREAD

**Issue by idk-kid1214** [EvanatorM/ScuffedMinecraft#29]

**Comment by HappyGoFishing** [comment]
trusting windows to protect your pc is like trusting the CIA/Mossad to not spy on you.
Its most likely because the executable isnt signed.

**Comment by GelbEinhalb** [comment]
Hi @idk-kid1214
Thanks for bringing this up!

As @HappyGoFishing already pointed out: 

What youre encountering is a common issue with unsigned executables. Windows flags programs as "potentially unsafe" if they arent signed with a trusted digital certificate. This doesn't necessarily mean the program is harmful -> it is just a precaution Windows takes for any unsigned or unknown software.

If you still want to run the program, you can bypass the warning by clicking **More info** and then selecting **Run anyway**.
