### ISSUE TITLE
you should use nullptr instead of NULL, for checking if pointers are null in c++.

### ISSUE THREAD

**Issue by HappyGoFishing** [EvanatorM/ScuffedMinecraft#3]
Checking if a pointer is NULL is technically correct, but its the C-way of doing things. In c++ there is a dedicated keyword, nullptr that should be used instead.

**Comment by EvanatorM** [comment]
Thanks for looking through the code! This will be fixed in the next release

**Comment by EvanatorM** [comment]
This has been resolved
