### ISSUE TITLE
Game fails to render on Linux

### ISSUE THREAD

**Issue by Luna-devv** [EvanatorM/ScuffedMinecraft#9]
I pretty much doubt that Linux is supposed to work in any way shape or form, but hey, Linux is epic 👍🏼 

![image](https://github.com/user-attachments/assets/733b8b7c-4c5e-4e75-8602-54b443f5bb4d)

I compiled the game with cmake successfully but when launching I just get a black screen with the following errors:
```bash
Error reading shader source files
Error compiling vertex shader!
0:1(1): error: syntax error, unexpected end of file

Error compiling fragment shader!
0:1(1): error: syntax error, unexpected end of file

Error linking shader program!
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Error reading shader source files
Error compiling vertex shader!
0:1(1): error: syntax error, unexpected end of file

Error compiling fragment shader!
0:1(1): error: syntax error, unexpected end of file

Error linking shader program!
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Error reading shader source files
Error compiling vertex shader!
0:1(1): error: syntax error, unexpected end of file

... and so on ...
```
Here is my system information:
![image](https://github.com/user-attachments/assets/83ee4056-2cc8-4f5f-a0a0-75fb6624e38b)

**Comment by FoxMoss** [comment]
It runs properly on Linux, your working directory just needs to contain the resources/ directory.

**Comment by Luna-devv** [comment]
In the time I set up a windows vm it auto-magically fixed itself, even though the assets dir was in the same folder as the binary the whole time, scuffed
![image](https://github.com/user-attachments/assets/182126d7-c8c3-4ebc-acab-b23752a40adc)

**Comment by FoxMoss** [comment]
> scuffed

it does what it says on the tin

**Comment by fintmc** [comment]
as already said, it does what its supposed to. in the readme it says that you need to run it from the directory that the scuffed_mc binary is so cd into the bin directory and run it from there. or run it from file explorer

**Comment by Luna-devv** [comment]
It's a bit weird that it searches the asset dir in the directory I executed from, rather than from where the binary is
